name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Copy debug keystore
      run: mkdir -p $HOME/.android && cp app/debug.keystore $HOME/.android/debug.keystore
      
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Build release APK
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE || 'app/release.keystore' }}
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD || 'pomodoroapk' }}
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS || 'androidreleasekey' }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD || 'pomodoroapk' }}
      run: ./gradlew assembleRelease
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/pomodoro-focus-debug.apk
        
    - name: Upload Release APK
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/pomodoro-focus.apk 